pipeline {
    agent any

    environment {
        MVN_HOME = tool 'Maven 3.9.0'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    // Use the Maven tool defined in the environment block
                    sh "${MVN_HOME}/bin/mvn -B -DskipTests clean package"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Use the Maven tool defined in the environment block
                    sh "${MVN_HOME}/bin/mvn test"
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
